fix(repo): correct Jest workspace configuration
There were duplicates in Jest configuration. This causes errors in any
tool using Jest that checks for invalid configuration, say
`vscode-jest`:

```text
Error: Whoops! Two projects resolved to the same config path:
C:\develop\nx-dotnet\packages\utils\jest.config.js:

  Project 1: C:/develop/nx-dotnet/packages/utils
  Project 2: C:/develop/nx-dotnet/packages/utils
```

Thanks!